export const ADD_DISCIPLINE = 'ADD_DISCIPLINE';
export const REMOVE_DISCIPLINE_FROM_SCHEDULE = 'REMOVE_DISCIPLINE_FROM_SCHEDULE';
export const REMOVE_DISCIPLINE_FROM_DISCIPLINE = 'REMOVE_DISCIPLINE_FROM_DISCIPLINE';